---
cloud_controller_uri: api.vcap.me
service:
  name: echo
  version: "1.0"
  description: 'Echo service'
  plans: ['free']
  default_plan: free
  tags: ['echo', 'echo-1.0', 'echobased', 'demo']
  timeout: 15
  supported_versions: ['1.0']
  version_aliases:
    "current": "1.0"
ip_route: 192.168.10.130
index: 0
token: changeechotoken
logging:
  level: debug
mbus: nats://nats:nats@192.168.10.130:4222
pid: /var/vcap/sys/run/echo_service.pid
node_timeout: 2
